"""
Figures package for RH Constraint-Diagnostic Demo.

Generates the required figures:
- fig01: Residual Ladder
- fig02: Phase Map (generated by sweep)
- fig03: Constraint Waterfall
- fig04: Positivity Wall
- fig05: Collapse Geometry
- fig06: Zero Overlay
- fig07: Falsification
"""

from .residual_ladder import generate_residual_ladder
from .constraint_waterfall import generate_constraint_waterfall
from .positivity_wall import generate_positivity_wall, generate_positivity_wall_sweep
from .collapse_geometry import generate_collapse_geometry
from .zero_overlay import generate_zero_overlay
from .falsification import generate_falsification
from .phase_map import generate_phase_map

__all__ = [
    "generate_residual_ladder",
    "generate_constraint_waterfall",
    "generate_positivity_wall",
    "generate_positivity_wall_sweep",
    "generate_collapse_geometry",
    "generate_zero_overlay",
    "generate_falsification",
    "generate_phase_map",
]
