"""
Figure 02: Phase Map.

Heatmap over two parameters showing pass/fail status or residual magnitude.
Generated by parameter sweep.
"""

import io
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from typing import Dict, List, Any, Optional


def generate_phase_map(
    sweep_results: Dict[str, Any],
    param1_name: str = "cell_count",
    param2_name: str = "propagation_range",
) -> bytes:
    """
    Generate phase map from sweep results.

    Args:
        sweep_results: Dictionary with sweep data
        param1_name: Name of first parameter (x-axis)
        param2_name: Name of second parameter (y-axis)

    Returns:
        PNG image as bytes
    """
    # Extract grid data
    param1_values = sweep_results.get("param1_values", [8, 16, 32])
    param2_values = sweep_results.get("param2_values", [1, 2, 3])
    results_grid = sweep_results.get("results_grid", {})

    # Build matrices
    n1, n2 = len(param1_values), len(param2_values)
    pass_matrix = np.zeros((n2, n1))
    residual_matrix = np.ones((n2, n1))
    max_level_matrix = np.zeros((n2, n1))

    for i, p1 in enumerate(param1_values):
        for j, p2 in enumerate(param2_values):
            key = f"{p1}_{p2}"
            if key in results_grid:
                result = results_grid[key]
                pass_matrix[j, i] = 1.0 if result.get("all_passed", False) else 0.0
                residual_matrix[j, i] = result.get("total_residual", 1.0)
                max_level_matrix[j, i] = result.get("max_level_passed", 0)

    # Create figure with multiple views
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))

    # Left: Pass/Fail heatmap
    ax1 = axes[0]
    im1 = ax1.imshow(pass_matrix, cmap='RdYlGn', aspect='auto',
                     vmin=0, vmax=1, origin='lower')
    ax1.set_xticks(np.arange(n1))
    ax1.set_yticks(np.arange(n2))
    ax1.set_xticklabels(param1_values)
    ax1.set_yticklabels(param2_values)
    ax1.set_xlabel(param1_name, fontsize=11)
    ax1.set_ylabel(param2_name, fontsize=11)
    ax1.set_title('Pass/Fail Status', fontsize=12, fontweight='bold')

    # Add text annotations
    for i in range(n1):
        for j in range(n2):
            text = '✓' if pass_matrix[j, i] > 0.5 else '✗'
            color = 'white'
            ax1.text(i, j, text, ha='center', va='center', fontsize=12,
                    fontweight='bold', color=color)

    plt.colorbar(im1, ax=ax1, shrink=0.8, label='Pass (1) / Fail (0)')

    # Middle: Residual heatmap (log scale)
    ax2 = axes[1]
    log_residuals = np.log10(np.clip(residual_matrix, 1e-16, 1))
    im2 = ax2.imshow(log_residuals, cmap='viridis_r', aspect='auto', origin='lower')
    ax2.set_xticks(np.arange(n1))
    ax2.set_yticks(np.arange(n2))
    ax2.set_xticklabels(param1_values)
    ax2.set_yticklabels(param2_values)
    ax2.set_xlabel(param1_name, fontsize=11)
    ax2.set_ylabel(param2_name, fontsize=11)
    ax2.set_title('Total Residual (log10)', fontsize=12, fontweight='bold')

    # Add value annotations
    for i in range(n1):
        for j in range(n2):
            val = residual_matrix[j, i]
            ax2.text(i, j, f'{val:.0e}', ha='center', va='center',
                    fontsize=8, color='white')

    plt.colorbar(im2, ax=ax2, shrink=0.8, label='log10(residual)')

    # Right: Max level passed
    ax3 = axes[2]
    im3 = ax3.imshow(max_level_matrix, cmap='Blues', aspect='auto',
                     vmin=0, vmax=4, origin='lower')
    ax3.set_xticks(np.arange(n1))
    ax3.set_yticks(np.arange(n2))
    ax3.set_xticklabels(param1_values)
    ax3.set_yticklabels(param2_values)
    ax3.set_xlabel(param1_name, fontsize=11)
    ax3.set_ylabel(param2_name, fontsize=11)
    ax3.set_title('Max Level Passed', fontsize=12, fontweight='bold')

    # Add level annotations
    for i in range(n1):
        for j in range(n2):
            level = int(max_level_matrix[j, i])
            ax3.text(i, j, f'L{level}', ha='center', va='center',
                    fontsize=10, fontweight='bold', color='black')

    cbar3 = plt.colorbar(im3, ax=ax3, shrink=0.8, label='Level (0-4)')
    cbar3.set_ticks([0, 1, 2, 3, 4])
    cbar3.set_ticklabels(['L0', 'L1', 'L2', 'L3', 'L4'])

    plt.suptitle('Fig 02: Parameter Phase Map', fontsize=14, fontweight='bold', y=1.02)
    plt.tight_layout()

    # Save to bytes
    buf = io.BytesIO()
    plt.savefig(buf, format='png', dpi=150, bbox_inches='tight')
    plt.close(fig)
    buf.seek(0)

    return buf.read()
